version: "3"
services:
  mongo:
    container_name: auth-mongo-container
    image: mongo:4.2
    restart: always
    volumes:
      - ./data:/data/db:z
    ports:
      - "27017:27017"
  api:
    container_name: auth-container
    image: node:14
    working_dir: /usr/src/auth
    env_file: 
      - ./.env
    restart: always
    command: bash -c "npm install --only=prod && npm start"
    volumes: 
      - ./dist/:/usr/src/auth/dist/:z
      - ./package.json:/usr/src/auth/package.json:z
    ports: 
      - "3010:3010"
    links: 
      - mongo

